### PR TITLE
adds endpoint to get state data from a zipcode

### PR DESCRIPTION
**Pull request by sfishel18**
#24

### CODE REVIEW

**Comment by sfishel18** [comment]
👋 hello! new contributor here. this seemed like a good first issue to start learning about the code base. i do have a few questions though:

1. am i on the wrong track here? the issue said to use `/state/:zipcode` as a route, but i wasn't sure how to disambiguate that from the existing `/state/:name`. maybe the intention was to use the same route and check the input against both the `states` table and `zipcodes` table and see which matches?

2. i don't have much experience setting up dynamo db. since i'm adding a query for state by abbreviation, should i make any changes to the database schema to make that query performant?

3. i'd like to add another item to the "seed" items that are added to dynamo as part of `init-dynamodb.sh`, so that there's an item in the `zipcodes` table that matches an item in the `states` table. where does the data in those items come from?

**Comment by rgraue** [comment]
> 👋 hello! new contributor here. this seemed like a good first issue to start learning about the code base. i do have a few questions though:
> 
> 1. am i on the wrong track here? the issue said to use `/state/:zipcode` as a route, but i wasn't sure how to disambiguate that from the existing `/state/:name`. maybe the intention was to use the same route and check the input against both the `states` table and `zipcodes` table and see which matches?
> 2. i don't have much experience setting up dynamo db. since i'm adding a query for state by abbreviation, should i make any changes to the database schema to make that query performant?
> 3. i'd like to add another item to the "seed" items that are added to dynamo as part of `init-dynamodb.sh`, so that there's an item in the `zipcodes` table that matches an item in the `states` table. where does the data in those items come from?

hi, good to have you here!
1) yes, I like the solution here. I tend to stay away from using the same route for _too much_... I think what you have here is good, and can always refactor later if we want to swap to query params or json payloads to help differentiate
2) I wouldn't worry too much ab the schema for now. the data is pretty static and small right now. Plus I think it'll be nice to pivot away from dynamo to a more data agnostic position. ie this can work with dynamo, mongo, or any db to that. 
3) yes please add as much data as you want locally! https://github.com/climate-cooperative/home-energy-data-manager is where the data exists. Sorry it was private before. but should be public now.

**Review by rgraue — APPROVED** [review]

**Comment by rgraue** [comment]
@sfishel18 quick question? are you able to merge this PR in? we're still honing in what are security/practices are going to be!

**Comment by sfishel18** [comment]
> @sfishel18 quick question? are you able to merge this PR in? we're still honing in what are security/practices are going to be!

i checked before i added my new commit, and no it doesn't look like i'm able to merge PRs myself.

**Pull request merged**
